version: '3.9'
services:
  postgres:
    container_name: dbingo_pg
    image: postgres:14.1
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    container_name: dbingo_redis
    image: redis:6.2-alpine
    ports:
      - '127.0.0.1:6379:6379'
